other_configs:
  image_w: 224
  image_h: 224
  hidden_size: 768

model_config:
  vilt:
    heads:
      vqa2:
        - type: mlp
          loss: vqa2_mlp
          freeze: false
          lr_multiplier: 1.0
          in_dim: 768
          hidden_size: 1536
          num_labels: 3129
          pooler_name: bert_pooler
    losses:
      vqa2_mlp: logit_bce

    image_encoder:
      type: vit
      params:
        random_init: True
        pretrained_model_name: google/vit-base-patch16-224
        do_pooling: false
        hidden_dropout_prob: 0.1
        add_pooling_layer: False
        do_patch_embeddings: False
        image_size:
        - ${other_configs.image_w}
        - ${other_configs.image_h}
        hidden_dim: ${other_configs.hidden_size}
        pretrained_model: vit_base_patch16_224
        mlp_dim: 3072

    image_embeddings:
      type: vilt_img_embedding
      image_size:
      - ${other_configs.image_w}
      - ${other_configs.image_h}
      hidden_dropout_prob: 0
      hidden_size: ${other_configs.hidden_size}
      patch_size: 16
      num_channels: 3
      random_init: True

    text_embeddings:
      type: vilt_text_embedding
      bert_model_name: bert-base-uncased
      hidden_dim: ${other_configs.hidden_size}
      hidden_size: 768
